scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backoffice_backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['php-backoffice-backend:8040']

  - job_name: 'backoffice_frontend'
    scrape_interval: 5s
    static_configs:
      - targets: ['php-backoffice-frontend:8041']

  - job_name: 'web_backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['php-web-backend:8030']
