services:
  # Databases
  Doctrine\ORM\EntityManager:
    factory: [ Pokedex\Backoffice\Shared\Infrastructure\Doctrine\BackofficeEntityManagerFactory, create ]
    arguments:
      - driver: '%env(BACKOFFICE_DATABASE_DRIVER)%'
        host: '%env(BACKOFFICE_DATABASE_HOST)%'
        port: '%env(BACKOFFICE_DATABASE_PORT)%'
        dbname: '%env(BACKOFFICE_DATABASE_NAME)%'
        user: '%env(BACKOFFICE_DATABASE_USER)%'
        password: '%env(BACKOFFICE_DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: pokedex.database_connection }
    public: true

  # Pokemon
  Pokedex\Backoffice\Pokemon\Domain\PokemonRepository: '@Pokedex\Backoffice\Pokemon\Infrastructure\Persistence\MySqlPokemonRepository'