services:
  # Databases
  # @todo this should be from backoffice, no web
  Doctrine\ORM\EntityManager:
    factory: [ Pokedex\Web\Shared\Infrastructure\Doctrine\WebEntityManagerFactory, create ]
    arguments:
      - driver: '%env(WEB_DATABASE_DRIVER)%'
        host: '%env(WEB_DATABASE_HOST)%'
        port: '%env(WEB_DATABASE_PORT)%'
        dbname: '%env(WEB_DATABASE_NAME)%'
        user: '%env(WEB_DATABASE_USER)%'
        password: '%env(WEB_DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: pokedex.database_connection }
    public: true
